import type { RequiredDataFromCollectionSlug } from 'payload'

export const pengajuanLowonganForm: RequiredDataFromCollectionSlug<'forms'> = {
  title: 'Pengajuan Lowongan',
  confirmationType: 'message',
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Terima kasih. Lowongan akan ditinjau admin sebelum ditampilkan di situs.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  emails: [],
  fields: [
    {
      name: 'position',
      blockType: 'text',
      label: 'Posisi',
      required: true,
      width: 100,
    },
    {
      name: 'companyName',
      blockType: 'text',
      label: 'Nama Perusahaan',
      required: true,
      width: 50,
    },
    {
      name: 'location',
      blockType: 'text',
      label: 'Lokasi Kerja (Kota/Daerah)',
      required: false,
      width: 50,
    },
    {
      name: 'workSetup',
      blockType: 'select',
      label: 'Sistem Kerja',
      required: false,
      options: [
        { label: 'On-site', value: 'on_site' },
        { label: 'Hybrid', value: 'hybrid' },
        { label: 'Remote', value: 'remote' },
      ],
      width: 50,
    },
    {
      name: 'employmentType',
      blockType: 'select',
      label: 'Jenis Pekerjaan',
      required: true,
      options: [
        { label: 'Kerja Praktik (KP)', value: 'kp' },
        { label: 'Magang (Internship)', value: 'magang' },
        { label: 'Full Time', value: 'full_time' },
      ],
      width: 50,
    },
    {
      name: 'experienceLevel',
      blockType: 'select',
      label: 'Tingkat Pengalaman',
      required: false,
      options: [
        { label: 'Entry Level (Fresh Graduate)', value: 'entry' },
        { label: 'Mid Level (1-3 Tahun)', value: 'mid' },
        { label: 'Senior Level (3-5+ Tahun)', value: 'senior' },
        { label: 'Executive/Managerial', value: 'executive' },
      ],
      width: 50,
    },
    {
      name: 'salaryRange',
      blockType: 'text',
      label: 'Rentang Gaji (Opsional)',
      required: false,
      width: 50,
    },
    {
      name: 'contactWhatsApp',
      blockType: 'text',
      label: 'Nomor WhatsApp Kontak (Opsional)',
      required: false,
      width: 50,
    },
    {
      name: 'officialLink',
      blockType: 'text',
      label: 'Tautan Resmi Lowongan (Opsional)',
      required: false,
      width: 50,
    },
    {
      name: 'jobDescription',
      blockType: 'textarea',
      label: 'Deskripsi Pekerjaan',
      required: true,
      width: 100,
    },
  ],
  submitButtonLabel: 'Kirim pengajuan',
}
