import type { RequiredDataFromCollectionSlug } from 'payload'

export const usahaAlumniForm: RequiredDataFromCollectionSlug<'forms'> = {
  title: 'Pengajuan Usaha Alumni',
  confirmationType: 'message',
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Terima kasih. Pengajuan akan ditinjau admin sebelum ditampilkan di situs.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  emails: [],
  fields: [
    {
      name: 'ownerName',
      blockType: 'text',
      label: 'Pemilik Usaha',
      required: true,
      width: 100,
    },
    {
      name: 'businessName',
      blockType: 'text',
      label: 'Nama Usaha',
      required: true,
      width: 100,
    },
    {
      name: 'category',
      blockType: 'select',
      label: 'Kategori',
      required: true,
      options: [
        { label: 'Manufaktur', value: 'manufaktur' },
        { label: 'Jasa', value: 'jasa' },
        { label: 'F&B', value: 'fnb' },
        { label: 'Teknologi', value: 'teknologi' },
        { label: 'Lainnya', value: 'lainnya' },
      ],
      width: 100,
    },
    {
      name: 'description',
      blockType: 'textarea',
      label: 'Narasi/Deskripsi Usaha',
      required: true,
      width: 100,
    },
    {
      name: 'productsOrServices',
      blockType: 'text',
      label: 'Produk / jasa',
      required: true,
      width: 100,
    },
    {
      name: 'address',
      blockType: 'textarea',
      label: 'Alamat',
      required: true,
      width: 100,
    },
    {
      name: 'phoneNumber',
      blockType: 'text',
      label: 'No. Telepon',
      required: true,
      width: 50,
    },
    {
      name: 'email',
      blockType: 'email',
      label: 'Email',
      required: false,
      width: 50,
    },
    {
      name: 'website',
      blockType: 'text',
      label: 'Link Resmi Usaha (Website)',
      required: false,
      width: 50,
    },
    {
      name: 'instagram',
      blockType: 'text',
      label: 'Link Resmi Usaha (Instagram) (Opsional)',
      required: false,
      width: 50,
    },
  ],
  submitButtonLabel: 'Kirim pengajuan',
}
